<a href="https://colab.research.google.com/github/d0k7/R-Programming-Language-Lab-Code/blob/main/R_LAB_UNIT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q1)Create and store a three-dimensional array with six layers of a 4 X 2 matrix, filled with a decreasing sequence of values between 4.8 and 0.1 of the appropriate length.



# Create the sequence of values
sequence_values <- seq(4.8, 0.1, length.out = 4*2*6)

# Reshape the sequence into a 4 X 2 X 6 array
three_dim_array <- array(sequence_values, dim = c(4, 2, 6))
print(three_dim_array)



, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9

, , 6

     [,1] [,2]
[1,]  0.8  0.4
[2,]  0.7  0.3
[3,]  0.6  0.2
[4,]  0.5  0.1



In [2]:
#Q2) Extract and store as a new object the fourth- and first-row elements, in that order, of the second column only of all layers of(1).



# Extract the elements
extracted_elements <- three_dim_array[c(4, 1), 2, ]
print(extracted_elements)



     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  4.1  3.3  2.5  1.7  0.9  0.1
[2,]  4.4  3.6  2.8  2.0  1.2  0.4


In [3]:
#Q3) Use a fourfold repetition of the second row of the matrix formed in (2) to fill a new array of dimensions 2 X 2 X 2 X



# Create the new array with fourfold repetition of the second row
repeated_array <- array(rep(extracted_elements, times = 4), dim = c(2, 2, 2, 4))
print(repeated_array)


, , 1, 1

     [,1] [,2]
[1,]  4.1  3.3
[2,]  4.4  3.6

, , 2, 1

     [,1] [,2]
[1,]  2.5  1.7
[2,]  2.8  2.0

, , 1, 2

     [,1] [,2]
[1,]  0.9  0.1
[2,]  1.2  0.4

, , 2, 2

     [,1] [,2]
[1,]  4.1  3.3
[2,]  4.4  3.6

, , 1, 3

     [,1] [,2]
[1,]  2.5  1.7
[2,]  2.8  2.0

, , 2, 3

     [,1] [,2]
[1,]  0.9  0.1
[2,]  1.2  0.4

, , 1, 4

     [,1] [,2]
[1,]  4.1  3.3
[2,]  4.4  3.6

, , 2, 4

     [,1] [,2]
[1,]  2.5  1.7
[2,]  2.8  2.0



In [4]:
#Q4) Create a new array comprised of the results of deleting the sixth layer of(1).


# Delete the sixth layer
modified_array <- three_dim_array[, , -6]
print(modified_array)


, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9



In [5]:
#Q5) Overwrite the second and fourth row elements of the second column of layers 1, 3 and 5 of(4) with -99.


# Overwrite specific elements in layers 1, 3, and 5
modified_array[c(2, 4), 2, c(1, 3, 5)] <- -99
print(modified_array)


, , 1

     [,1]  [,2]
[1,]  4.8   4.4
[2,]  4.7 -99.0
[3,]  4.6   4.2
[4,]  4.5 -99.0

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1]  [,2]
[1,]  3.2   2.8
[2,]  3.1 -99.0
[3,]  3.0   2.6
[4,]  2.9 -99.0

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1]  [,2]
[1,]  1.6   1.2
[2,]  1.5 -99.0
[3,]  1.4   1.0
[4,]  1.3 -99.0

